//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/Game_Assets/Scripts/Own Scripts/InputControls/UI_Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @UI_Controls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @UI_Controls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""UI_Controls"",
    ""maps"": [
        {
            ""name"": ""UI_Input"",
            ""id"": ""73380ad4-04f1-431f-be73-97c96e8ea95e"",
            ""actions"": [
                {
                    ""name"": ""Escape for Pause"",
                    ""type"": ""Button"",
                    ""id"": ""27a784f8-6f73-4a22-9207-4014937f65b3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""aea00041-ac72-4369-9a4d-2e69eac4c38e"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyBoard"",
                    ""action"": ""Escape for Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""KeyBoard"",
            ""bindingGroup"": ""KeyBoard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // UI_Input
        m_UI_Input = asset.FindActionMap("UI_Input", throwIfNotFound: true);
        m_UI_Input_EscapeforPause = m_UI_Input.FindAction("Escape for Pause", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // UI_Input
    private readonly InputActionMap m_UI_Input;
    private List<IUI_InputActions> m_UI_InputActionsCallbackInterfaces = new List<IUI_InputActions>();
    private readonly InputAction m_UI_Input_EscapeforPause;
    public struct UI_InputActions
    {
        private @UI_Controls m_Wrapper;
        public UI_InputActions(@UI_Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @EscapeforPause => m_Wrapper.m_UI_Input_EscapeforPause;
        public InputActionMap Get() { return m_Wrapper.m_UI_Input; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UI_InputActions set) { return set.Get(); }
        public void AddCallbacks(IUI_InputActions instance)
        {
            if (instance == null || m_Wrapper.m_UI_InputActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_UI_InputActionsCallbackInterfaces.Add(instance);
            @EscapeforPause.started += instance.OnEscapeforPause;
            @EscapeforPause.performed += instance.OnEscapeforPause;
            @EscapeforPause.canceled += instance.OnEscapeforPause;
        }

        private void UnregisterCallbacks(IUI_InputActions instance)
        {
            @EscapeforPause.started -= instance.OnEscapeforPause;
            @EscapeforPause.performed -= instance.OnEscapeforPause;
            @EscapeforPause.canceled -= instance.OnEscapeforPause;
        }

        public void RemoveCallbacks(IUI_InputActions instance)
        {
            if (m_Wrapper.m_UI_InputActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IUI_InputActions instance)
        {
            foreach (var item in m_Wrapper.m_UI_InputActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_UI_InputActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public UI_InputActions @UI_Input => new UI_InputActions(this);
    private int m_KeyBoardSchemeIndex = -1;
    public InputControlScheme KeyBoardScheme
    {
        get
        {
            if (m_KeyBoardSchemeIndex == -1) m_KeyBoardSchemeIndex = asset.FindControlSchemeIndex("KeyBoard");
            return asset.controlSchemes[m_KeyBoardSchemeIndex];
        }
    }
    public interface IUI_InputActions
    {
        void OnEscapeforPause(InputAction.CallbackContext context);
    }
}
